// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMS.Infrastructure.Data;

#nullable disable

namespace QMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(QMSDbContext))]
    partial class QMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QMS.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QMS.Core.Entities.Kiosk", b =>
                {
                    b.Property<int>("KioskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KioskId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DefaultPrinterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KioskCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KioskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("KioskId");

                    b.HasIndex("DefaultPrinterId");

                    b.HasIndex("KioskCode")
                        .IsUnique();

                    b.ToTable("Kiosks");
                });

            modelBuilder.Entity("QMS.Core.Entities.PostProcessBranch", b =>
                {
                    b.Property<int>("PostProcessBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PostProcessBranchId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PostProcessBranchId");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.ToTable("PostProcessBranches");
                });

            modelBuilder.Entity("QMS.Core.Entities.PrintHistory", b =>
                {
                    b.Property<long>("PrintHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PrintHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PrintStatus")
                        .HasColumnType("int");

                    b.Property<int>("PrintType")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrintedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PrintedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PrintedByUserName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("PrinterIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PrintHistoryId");

                    b.HasIndex("TicketId");

                    b.ToTable("PrintHistories", (string)null);
                });

            modelBuilder.Entity("QMS.Core.Entities.Printer", b =>
                {
                    b.Property<int>("PrinterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrinterId"));

                    b.Property<string>("AreaCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConnectionType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PrinterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrinterType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PrinterId");

                    b.HasIndex("AreaCode");

                    b.HasIndex("PrinterCode")
                        .IsUnique();

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("QMS.Core.Entities.PrioritySetting", b =>
                {
                    b.Property<int>("PrioritySettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrioritySettingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InterleaveInterval")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Strategy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PrioritySettingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PrioritySettings");
                });

            modelBuilder.Entity("QMS.Core.Entities.QueueStatistic", b =>
                {
                    b.Property<long>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("StatId"));

                    b.Property<int>("AvgServiceTimeSeconds")
                        .HasColumnType("int");

                    b.Property<int>("AvgWaitTimeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxQueueSize")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<int?>("StatHour")
                        .HasColumnType("int");

                    b.Property<int>("TotalCancelled")
                        .HasColumnType("int");

                    b.Property<int>("TotalPassed")
                        .HasColumnType("int");

                    b.Property<int>("TotalProcessed")
                        .HasColumnType("int");

                    b.HasKey("StatId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StatDate");

                    b.HasIndex("RoomId", "StatDate", "StatHour")
                        .IsUnique();

                    b.ToTable("QueueStatistics");
                });

            modelBuilder.Entity("QMS.Core.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxQueueSize")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.HasIndex("ServiceId", "IsActive");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("QMS.Core.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ServiceId");

                    b.HasIndex("ServiceCode")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("QMS.Core.Entities.ServiceRoomBranchRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PostProcessBranchId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RuleId");

                    b.HasIndex("PostProcessBranchId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceRoomBranchRules");
                });

            modelBuilder.Entity("QMS.Core.Entities.TVAd", b =>
                {
                    b.Property<int>("TVAdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TVAdId"));

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("AdType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TVProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TVAdId");

                    b.HasIndex("TVProfileId");

                    b.ToTable("TVAds");
                });

            modelBuilder.Entity("QMS.Core.Entities.TVProfile", b =>
                {
                    b.Property<int>("TVProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TVProfileId"));

                    b.Property<string>("ActiveColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdPosition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AdSizePercent")
                        .HasColumnType("int");

                    b.Property<string>("AdVideoUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("ColumnGap")
                        .HasColumnType("int");

                    b.Property<int>("ColumnsPerRow")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionStatusColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CounterNumberFontSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DateTimeFontSize")
                        .HasColumnType("int");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("int");

                    b.Property<string>("FooterBgColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FooterFontSize")
                        .HasColumnType("int");

                    b.Property<string>("FooterPosition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FooterSizePercent")
                        .HasColumnType("int");

                    b.Property<string>("FooterText")
                        .HasColumnType("longtext");

                    b.Property<string>("FooterTextColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GridConfigJson")
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderBgColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HeaderSizePercent")
                        .HasColumnType("int");

                    b.Property<string>("HeaderTextColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HospitalNameFontSize")
                        .HasColumnType("int");

                    b.Property<string>("InactiveColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LayoutMode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("MainBgColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MainTextColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoomNameFontSize")
                        .HasColumnType("int");

                    b.Property<int>("RowGap")
                        .HasColumnType("int");

                    b.Property<int>("RowsCount")
                        .HasColumnType("int");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("int");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("int");

                    b.Property<bool>("ShowAd")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowDate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowFooter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TVCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TVName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TicketNumberFontSize")
                        .HasColumnType("int");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TVProfileId");

                    b.HasIndex("TVCode")
                        .IsUnique();

                    b.ToTable("TVProfiles");
                });

            modelBuilder.Entity("QMS.Core.Entities.TVProfileRoom", b =>
                {
                    b.Property<int>("TVProfileRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TVProfileRoomId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TVProfileId")
                        .HasColumnType("int");

                    b.HasKey("TVProfileRoomId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TVProfileId", "RoomId")
                        .IsUnique();

                    b.ToTable("TVProfileRooms");
                });

            modelBuilder.Entity("QMS.Core.Entities.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TicketId"));

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CalledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<int?>("KioskId")
                        .HasColumnType("int");

                    b.Property<int?>("PostProcessBranchId")
                        .HasColumnType("int");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityType")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTimeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ServingAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WaitTimeSeconds")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("CalledByUserId");

                    b.HasIndex("IssuedDate");

                    b.HasIndex("KioskId");

                    b.HasIndex("PostProcessBranchId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("TicketNumber", "IssuedDate")
                        .IsUnique();

                    b.HasIndex("RoomId", "Status", "IssuedDate");

                    b.HasIndex("ServiceId", "RoomId", "Status", "IssuedDate");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("QMS.Core.Entities.TicketSequence", b =>
                {
                    b.Property<int>("SequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SequenceId"));

                    b.Property<int>("NormalLastNumber")
                        .HasColumnType("int");

                    b.Property<int>("PriorityLastNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SequenceDate")
                        .HasColumnType("date");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("SequenceId");

                    b.HasIndex("ServiceId", "SequenceDate")
                        .IsUnique();

                    b.ToTable("TicketSequences");
                });

            modelBuilder.Entity("QMS.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AreaCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("RoomId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QMS.Core.Entities.WorkingSession", b =>
                {
                    b.Property<int>("WorkingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkingSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("WorkingSessionId");

                    b.ToTable("WorkingSessions");
                });

            modelBuilder.Entity("QMS.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("QMS.Core.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QMS.Core.Entities.Kiosk", b =>
                {
                    b.HasOne("QMS.Core.Entities.Printer", "DefaultPrinter")
                        .WithMany("Kiosks")
                        .HasForeignKey("DefaultPrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultPrinter");
                });

            modelBuilder.Entity("QMS.Core.Entities.PrintHistory", b =>
                {
                    b.HasOne("QMS.Core.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("QMS.Core.Entities.PrioritySetting", b =>
                {
                    b.HasOne("QMS.Core.Entities.Room", "Room")
                        .WithMany("PrioritySettings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QMS.Core.Entities.Service", "Service")
                        .WithMany("PrioritySettings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Room");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QMS.Core.Entities.QueueStatistic", b =>
                {
                    b.HasOne("QMS.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QMS.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QMS.Core.Entities.Room", b =>
                {
                    b.HasOne("QMS.Core.Entities.Service", "Service")
                        .WithMany("Rooms")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QMS.Core.Entities.ServiceRoomBranchRule", b =>
                {
                    b.HasOne("QMS.Core.Entities.PostProcessBranch", "PostProcessBranch")
                        .WithMany("BranchRules")
                        .HasForeignKey("PostProcessBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QMS.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QMS.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PostProcessBranch");

                    b.Navigation("Room");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QMS.Core.Entities.TVAd", b =>
                {
                    b.HasOne("QMS.Core.Entities.TVProfile", "TVProfile")
                        .WithMany("Advertisements")
                        .HasForeignKey("TVProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TVProfile");
                });

            modelBuilder.Entity("QMS.Core.Entities.TVProfileRoom", b =>
                {
                    b.HasOne("QMS.Core.Entities.Room", "Room")
                        .WithMany("TVProfileRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QMS.Core.Entities.TVProfile", "TVProfile")
                        .WithMany("TVProfileRooms")
                        .HasForeignKey("TVProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("TVProfile");
                });

            modelBuilder.Entity("QMS.Core.Entities.Ticket", b =>
                {
                    b.HasOne("QMS.Core.Entities.User", "CalledByUser")
                        .WithMany("CalledTickets")
                        .HasForeignKey("CalledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QMS.Core.Entities.Kiosk", "Kiosk")
                        .WithMany("Tickets")
                        .HasForeignKey("KioskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QMS.Core.Entities.PostProcessBranch", "PostProcessBranch")
                        .WithMany("Tickets")
                        .HasForeignKey("PostProcessBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QMS.Core.Entities.Printer", "Printer")
                        .WithMany("Tickets")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QMS.Core.Entities.Room", "Room")
                        .WithMany("Tickets")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QMS.Core.Entities.Service", "Service")
                        .WithMany("Tickets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalledByUser");

                    b.Navigation("Kiosk");

                    b.Navigation("PostProcessBranch");

                    b.Navigation("Printer");

                    b.Navigation("Room");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QMS.Core.Entities.TicketSequence", b =>
                {
                    b.HasOne("QMS.Core.Entities.Service", "Service")
                        .WithMany("TicketSequences")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QMS.Core.Entities.User", b =>
                {
                    b.HasOne("QMS.Core.Entities.Printer", "Printer")
                        .WithMany("Users")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QMS.Core.Entities.Room", "Room")
                        .WithMany("Users")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Printer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QMS.Core.Entities.Kiosk", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("QMS.Core.Entities.PostProcessBranch", b =>
                {
                    b.Navigation("BranchRules");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("QMS.Core.Entities.Printer", b =>
                {
                    b.Navigation("Kiosks");

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QMS.Core.Entities.Room", b =>
                {
                    b.Navigation("PrioritySettings");

                    b.Navigation("TVProfileRooms");

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QMS.Core.Entities.Service", b =>
                {
                    b.Navigation("PrioritySettings");

                    b.Navigation("Rooms");

                    b.Navigation("TicketSequences");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("QMS.Core.Entities.TVProfile", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("TVProfileRooms");
                });

            modelBuilder.Entity("QMS.Core.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CalledTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
